import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>
              {' '}
              The PAC DAO Founder Token is an ERC-721 NFT that doesn’t do
              anything or confer any special rights. It’s just a way to receive
              a memento of support for promoting a good cause. All proceeds are
              being used to fund the DAO, which is planning action campaigns in
              accordance with its mission: PAC is not actually a Political
              Action Committee, but an issue group that stands for People
              Advocating for Crypto
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>
              {' '}
              Since every NFT drop requires interesting tokenomics, PAC DAO has
              a fun way to reward early adopters. The initial mint price is very
              cheap, well below price of gas. However, the floor price increases
              by at least 7.5% after each mint, so early supporters get a nice
              discount. Additionally, the DAO address receives 10 additional
              tokens throughout the initial mint to distribute to the community
              as desired.
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>
              The other aspect built into the minting mechanics is that anybody
              who likes can choose to raise the stakes by minting at any amount
              above the floor price. Should some whale choose to do this, the
              new floor price would raise accordingly, and the supply would be
              massively curtailed.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Even if people just mint at floor price, the effective supply is
              effectively scarce.
            </p>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              In reality these numbers could be higher if whales choose to
              accelerate the floor price. These are the{' '}
              <a
                href="https://github.com/PacDAO/founder-token"
                target="_blank"
                rel="noreferrer"
              >
                experimental results derived from the Brownie tests
              </a>{' '}
              included in the GitHub repository. If you’re technical, it’s a
              great idea to read through it to understand the mechanics, or
              check out the token deployed at{' '}
              <a href="https://etherscan.io/address/0x63994b223f01b943eff986b1b379312508dc15f8">
                {/* {abbrAddress('0x63994b223f01b943eff986b1b379312508dc15f8')} */}
              </a>
            </p>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Assuming everybody just mints at floor price, the badge will be
              cheaper than gas for about the first 50 coins. By NFT 100, the
              token will cost about half an ETH. By 200, only millionaires will
              be able to afford it. By 300, only billionaires will be able to
              afford it. The theoretical cap is some number shortly thereafter
              when overflow errors would prevent minting. Practically, it would
              be a pleasant surprise if a hundred get minted.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
